site_name: Maze Algorithm Notes
repo_url: https://github.com/NeonOrangeOrange/maze-algorithm-notes/
edit_uri: ""
site_url: https://NeonOrangeOrange.github.io/maze-algorithm-notes/

nav:
  - Home: index.md
  - Maze Generation:
    - Funamental Generation Algorithms: fundamental_generation.md
  - Maze Solving:
    - Fundamental Solving Algorithms: fundamental_solving.md
  - Demos: demos/index.md
 
