site_name: Maze Algorithm Notes - NOO
repo_url: https://github.com/NeonOrangeOrange/maze-generation-notes

nav:
  - Home: index.md
  - Maze Generation:
    - Funamental Generation Algorithms: fundamental_generation.md
  - Maze Solving:
    - Fundamental Solving Algorithms: fundamental_solving.md
  - Demos: demos/index.md
 
