site_name: My Docs


nav:
  - Home: index.md
  - Maze Generation:
    - Funamental Generation Algorithms: fundamental_generation.md
  - Maze Solving:
    - Fundamental Solving Algorithms: fundamental_solving.md
  - Demos: demos/index.md
 
